### ISSUE TITLE
cant make this script to work. got an error when run command

### ISSUE THREAD

**Issue by Optimusik** [vandrw/lostpaw-transformer#1]
i try to run script but get an error

C:\Users\Asus\Downloads\lostpaw-transformer-main\lostpaw-transformer>python scripts/train.py -c lostpaw/configs/default.yaml --info_path "output/data/train.data"
C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\vit\feature_extraction_vit.py:28: FutureWarning: The class ViTFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use ViTImageProcessor instead.
  warnings.warn(
[INFO] No model to load. Training from scratch.
Traceback (most recent call last):
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\base.py", line 3652, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'source'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Asus\Downloads\lostpaw-transformer-main\lostpaw-transformer\scripts\train.py", line 21, in <module>
    main(args)
  File "C:\Users\Asus\Downloads\lostpaw-transformer-main\lostpaw-transformer\scripts\train.py", line 11, in main
    trainer = Trainer(config, pet_data)
  File "C:\Users\Asus\Downloads\lostpaw-transformer-main\lostpaw-transformer\lostpaw\model\trainer.py", line 54, in __init__
    data_folder = PetImagesFolder(info_path.parent, info_path.name)
  File "C:\Users\Asus\Downloads\lostpaw-transformer-main\lostpaw-transformer\lostpaw\data\data_folder.py", line 29, in __init__
    self.sources = df["source"].tolist()
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\base.py", line 3654, in get_loc
    raise KeyError(key) from err
KeyError: 'source'

What is this "source"? There is no definition in description about source.

this is my train,data contents
{"pet_id": "1", "paths": ["output/data/1/0.jpg", "output/data/1/1.jpg", "output/data/1/2.jpg", "output/data/1/3.jpg", "output/data/1/4.jpg"]}
{"pet_id": "2", "paths": ["output/data/2/0.jpg", "output/data/2/1.jpg", "output/data/2/2.jpg", "output/data/2/3.jpg"]}

**Comment by vandrw** [comment]
That was a remainder from the data augmentation step. We preserved the "source" so that it can be used to remove duplicates from the dataset. We've now made source optional. Please let us know if there are any other issues!
